FROM node:20-alpine AS base
WORKDIR /app
COPY package.json yarn.lock ./
COPY backend/package.json ./backend/
RUN yarn install --production --frozen-lockfile

FROM node:20-alpine
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY backend ./backend
COPY database ./database
RUN addgroup -S dcms && adduser -S dcms -G dcms
USER dcms
EXPOSE 3001
WORKDIR /app/backend
CMD ["node", "src/index.js"]
